name: QField SDK → Discord Polling

on:
  schedule:
    - cron: '* * * * *'        # chaque minute
  workflow_dispatch:           # bouton “Run workflow”

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install qfieldcloud-sdk requests

      - name: Run notifier
        run: python notifier.py
